name: Update Data

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Install required R packages
        run: |
          install.packages(c("stringr", "httr2", "jsonlite", "dotenv"), repos = "https://packagemanager.posit.co/cran/__linux__/jammy/latest")
        shell: Rscript {0}

      - name: Execute data download script
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          USER: ${{ secrets.API_USER }}
          PASSWORD: ${{ secrets.API_PASSWORD }}
        run: Rscript interlight_api.R

      - name: Commit and push new data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated data update: New JSON files added"
          file_pattern: "data/"

      - name: Trigger Dashboard Repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TRIGGER_DASHBOARD }}
          repository: 'FORWARDS-TREAD/forwards-tread.github.io'
          event-type: 'data-updated-event'
